server:
  port: 8081
  
spring:
  application:
    name: spring-oauth-sso-demo

management:
  context-path: /actuator
  security:
    enabled: false

logging:
  level:
    org.springframework.security: DEBUG
    com.benwilcock: DEBUG
  file: c:/var/spring-oauth-sso-demo.log

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
    
github:
  client:
    clientId: a19290d4de4dd9b0138f
    clientSecret: 191ab8b51e811d427a5a25ff55aa95432812f89b
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

google:
  client:
    clientId: <your-id-here>
    clientSecret: <your-secret-here>
    accessTokenUri: https://www.googleapis.com/oauth2/v3/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: profile
  resource:
    userInfoUri: https://www.googleapis.com/userinfo/v2/me
    preferTokenInfo: true

uaa:
  client:
    clientId: spring-oauth-sso-demo
    clientSecret: secret
    checkTokenUrl: http://localhost:8080/uaa/check_token
    accessTokenUri: http://localhost:8080/uaa/oauth/token
    approvalsUri: http://localhost:8080/uaa/approvals
    userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
  resource:
    userInfoUri: http://localhost:8080/uaa/userinfo
    
oauth2-vanilla:
  client:
    accessTokenUri: http://localhost:9991/uaa/oauth/token
    userAuthorizationUri: http://localhost:9991/uaa/oauth/authorize
    clientId: acme
    clientSecret: acmesecret
  resource:
    userInfoUri: http://localhost:9991/uaa/user    